#ifndef _VL53L1_PRESET_SETUP_H_
#define _VL53L1_PRESET_SETUP_H_
#ifdef __cplusplus
extern "C"
{
#endif
enum VL53L1_Tuning_t {
	VL53L1_TUNING_VERSION = 0,
	VL53L1_TUNING_PROXY_MIN,
	VL53L1_TUNING_SINGLE_TARGET_XTALK_TARGET_DISTANCE_MM,
	VL53L1_TUNING_SINGLE_TARGET_XTALK_SAMPLE_NUMBER,
	VL53L1_TUNING_MIN_AMBIENT_DMAX_VALID,
	VL53L1_TUNING_MAX_SIMPLE_OFFSET_CALIBRATION_SAMPLE_NUMBER,
	VL53L1_TUNING_XTALK_FULL_ROI_TARGET_DISTANCE_MM,
	VL53L1_TUNING_SIMPLE_OFFSET_CALIBRATION_REPEAT,
	VL53L1_TUNING_MAX_TUNABLE_KEY
};
#define TUNING_VERSION	0x0004
#define TUNING_PROXY_MIN -30 
#define TUNING_SINGLE_TARGET_XTALK_TARGET_DISTANCE_MM 600
#define TUNING_SINGLE_TARGET_XTALK_SAMPLE_NUMBER 50
#define TUNING_MIN_AMBIENT_DMAX_VALID 8
#define TUNING_MAX_SIMPLE_OFFSET_CALIBRATION_SAMPLE_NUMBER 50
#define TUNING_XTALK_FULL_ROI_TARGET_DISTANCE_MM 600
#define TUNING_SIMPLE_OFFSET_CALIBRATION_REPEAT 1
#ifdef __cplusplus
}
#endif
#endif 